min_log_level: "debug"
http_port: 1234
read_timeout: 10
write_timeout: 5
postgresql:
  host: "localhost"
  port: 5432
  user: "user"
  password: "user"
  name: "postgres"
redis:
  host: "redis"
  port: 6379
